const ALL_ORDERS = {
  REQUEST: 'ALL_ORDERS_REQUEST',
  SUCCESS: 'ALL_ORDERS_SUCCESS',
  FAILURE: 'ALL_ORDERS_FAILURE',
};

const CREATE_ORDER = {
  REQUEST: 'CREATE_ORDER_REQUEST',
  SUCCESS: 'CREATE_ORDER_SUCCESS',
  FAILURE: 'CREATE_ORDER_FAILURE',
};

const UPDATE_ORDER = {
  REQUEST: 'UPDATE_ORDER_REQUEST',
  SUCCESS: 'UPDATE_ORDER_SUCCESS',
  FAILURE: 'UPDATE_ORDER_FAILURE',
  RESET: 'UPDATE_ORDER_RESET',
};

const DELETE_ORDER = {
  REQUEST: 'DELETE_ORDER_REQUEST',
  SUCCESS: 'DELETE_ORDER_SUCCESS',
  FAILURE: 'DELETE_ORDER_FAILURE',
  RESET: 'DELETE_ORDER_RESET',
};

const MY_ORDER = {
  REQUEST: 'MY_ORDER_REQUEST',
  SUCCESS: 'MY_ORDER_SUCCESS',
  FAILURE: 'MY_ORDER_FAILURE',
};

const ORDER_DETAILS = {
  REQUEST: 'ORDER_DETAILS_REQUEST',
  SUCCESS: 'ORDER_DETAILS_SUCCESS',
  FAILURE: 'ORDER_DETAILS_FAILURE',
};

const CLEAR_ERROR = 'CLEAR_ERROR';

export {
  CREATE_ORDER,
  CLEAR_ERROR,
  MY_ORDER,
  ORDER_DETAILS,
  ALL_ORDERS,
  UPDATE_ORDER,
  DELETE_ORDER,
};
