const ALL_PRODUCTS = {
  REQUEST: 'ALL_PRODUCTS_REQUEST',
  SUCCESS: 'ALL_PRODUCTS_SUCCESS',
  FAILURE: 'ALL_PRODUCTS_FAILURE',
};

const NEW_PRODUCT = {
  REQUEST: 'NEW_PRODUCT_REQUEST',
  SUCCESS: 'NEW_PRODUCT_SUCCESS',
  FAILURE: 'NEW_PRODUCT_FAILURE',
  RESET: 'NEW_PRODUCT_RESET',
};

const DELETE_PRODUCT = {
  REQUEST: 'DELETE_PRODUCT_REQUEST',
  SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  FAILURE: 'DELETE_PRODUCT_FAILURE',
  RESET: 'DELETE_PRODUCT_RESET',
};

const UPDATE_PRODUCT = {
  REQUEST: 'UPDATE_PRODUCT_REQUEST',
  SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  FAILURE: 'UPDATE_PRODUCT_FAILURE',
  RESET: 'UPDATE_PRODUCT_RESET',
};

const ADMIN_PRODUCTS = {
  REQUEST: 'ADMIN_PRODUCTS_REQUEST',
  SUCCESS: 'ADMIN_PRODUCTS_SUCCESS',
  FAILURE: 'ADMIN_PRODUCTS_FAILURE',
};

const PRODUCT_DETAILS = {
  REQUEST: 'PRODUCT_DETAILS_REQUEST',
  SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  FAILURE: 'PRODUCT_DETAILS_FAILURE',
};

const PRODUCT_REVIEW = {
  REQUEST: 'PRODUCT_REVIEW_REQUEST',
  SUCCESS: 'PRODUCT_REVIEW_SUCCESS',
  FAILURE: 'PRODUCT_REVIEW_FAILURE',
  RESET: 'PRODUCT_REVIEW_RESET',
};

const DELETE_REVIEW = {
  REQUEST: 'DELETE_REVIEW_REQUEST',
  SUCCESS: 'DELETE_REVIEW_SUCCESS',
  FAILURE: 'DELETE_REVIEW_FAILURE',
  RESET: 'DELETE_REVIEW_RESET',
};

const ALL_REVIEW = {
  REQUEST: 'ALL_REVIEW_REQUEST',
  SUCCESS: 'ALL_REVIEW_SUCCESS',
  FAILURE: 'ALL_REVIEW_FAILURE',
};

const CLEAR_ERROR = 'CLEAR_ERROR';

export {
  ALL_PRODUCTS,
  PRODUCT_DETAILS,
  CLEAR_ERROR,
  PRODUCT_REVIEW,
  ADMIN_PRODUCTS,
  NEW_PRODUCT,
  DELETE_PRODUCT,
  UPDATE_PRODUCT,
  ALL_REVIEW,
  DELETE_REVIEW,
};
